// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/22/2026, 3:05:07 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/ula/Documents/remont/Corporate Website Development/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ula/Documents/remont/Corporate Website Development/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ula/Documents/remont/Corporate Website Development/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ula/Documents/remont/Corporate Website Development/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ula/Documents/remont/Corporate Website Development/plugins/**/*.{js,ts,mjs}","/Users/ula/Documents/remont/Corporate Website Development/composables/**/*.{js,ts,mjs}","/Users/ula/Documents/remont/Corporate Website Development/utils/**/*.{js,ts,mjs}","/Users/ula/Documents/remont/Corporate Website Development/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ula/Documents/remont/Corporate Website Development/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ula/Documents/remont/Corporate Website Development/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ula/Documents/remont/Corporate Website Development/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;